name: Build nvidia driver
on:
  workflow_call:
env:
    IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
    NVIDIA_MAJOR_VERSION: 555
    BASE_IMAGE: quay.io/fedora-ostree-desktops/silverblue

jobs:    
  push-ghcr:
    name: Build and push image
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        version: [40]
      fail-fast: false

    steps:
      # Checkout push-to-registry action GitHub repository
      - name: Checkout Push to Registry action
        uses: actions/checkout@v4

      - name: Variables
        run: |
            REPO=${{ github.repository }}
            echo "IMAGE_NAME=nvidia-${REPO##*/}" >> $GITHUB_ENV
            echo "FEDORA_MAJOR_VERSION=${{ matrix.version }}" >> $GITHUB_ENV
            
      # Build image using Buildah action
      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            ./Containerfile
          image: |
            quay.io/fedora-ostree-desktops/silverblue
          tags: |
            latest
          build-args: |
            BASE_IMAGE=${{ env.BASE_IMAGE }}
            FEDORA_MAJOR_VERSION=${{ env.FEDORA_MAJOR_VERSION }}
            NVIDIA_MAJOR_VERSION=${{ env.NVIDIA_MAJOR_VERSION }}

          labels: ${{ steps.meta.outputs.labels }}
          oci: false
