name: Build Nvidia drivers
on:
  push:
    branches:
      - master
  pull_request:
  merge_group:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'
jobs:
  build-drv:
    runs-on: ubuntu-latest
    container:
      image: quay.io/fedora/fedora-minimal:${{ matrix.version }}
    strategy:
      matrix:
        version: [40, 41]
      fail-fast: false
    steps:
      - name: Install build env
        run: |
          if command -v dnf5 &> /dev/null; then; alias dnf=dnf5; fi
          dnf install tar curl gzip git -y
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run build script
        env:
          IS_LOCAL_BUILD: 0
        run: |
          $GITHUB_WORKSPACE/scripts/build-nvidia-drv.sh
          ls -la /tmp/nvidia-drv/rpmbuild/RPMS/x86_64
