name: Build Silverblue container
on:
  workflow_call:
env:
    IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
    NVIDIA_MAJOR_VERSION: 555
    BASE_IMAGE: quay.io/fedora-ostree-desktops/silverblue

jobs:    
  push-ghcr:
    name: Build and push image
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false

    steps: 
      # Build image using Buildah action
      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            ./Containerfile
          image: |
            ${{ env.IMAGE_NAME }}
          tags: |
            ${{ steps.generate-tags.outputs.alias_tags }}
          build-args: |
            BASE_IMAGE=${{ env.BASE_IMAGE }}
            FEDORA_MAJOR_VERSION=${{ env.FEDORA_MAJOR_VERSION }}
            NVIDIA_MAJOR_VERSION=${{ env.NVIDIA_MAJOR_VERSION }}

          labels: ${{ steps.meta.outputs.labels }}
          oci: false
