name: Build Nvidia drivers
on:
  push:
    branches:
      - master
  pull_request:
  merge_group:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'
jobs:
  build-drv:
    runs-on: ubuntu-latest
    container:
      image: quay.io/fedora/fedora:${{ matrix.version }}
    strategy:
      matrix:
        version: [40, 41]
      fail-fast: false
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run build script
        run: |
          $GITHUB_WORKSPACE/scripts/build-nvidia-drv.sh
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            /tmp/nvidia-drv/rpmbuild/RPMS/nvidia-drv-560.35.03.fc40.x86_64.tar.gz
            /tmp/nvidia-drv/rpmbuild/RPMS/nvidia-drv-560.35.03.fc41.x86_64.tar.gz
          name: "test release"
          body: "body"
          draft: true
          make_latest: true

