name: Build Nvidia drivers
on:
  push:
    branches:
      - master
  pull_request:
  merge_group:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'
jobs:
  build-drv:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: quay.io/fedora/fedora:${{ matrix.version }}
    strategy:
      matrix:
        version: [40, 41]
      fail-fast: false
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run build script
        id: run-build-script
        env:
          BUILD: false
        run: |
          $GITHUB_WORKSPACE/scripts/build-nvidia-drv.sh
      - name: Push version tag
      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "${{ steps.run-build-script.outputs.NVIDIA_VERSION }}"
          tag_exists_error: false
          message: "Driver ${{ steps.run-build-script.outputs.NVIDIA_VERSION }}"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            /tmp/nvidia-drv/rpmbuild/RPMS/*.tar.gz
          name: "Nvidia Drivers - ${{ steps.run-build-script.outputs.NVIDIA_VERSION }}"
          body: "${{ steps.run-build-script.outputs.NVIDIA_VERSION }}"
          draft: false
          make_latest: true

