name: Build Nvidia drivers
on:
  pull_request:
  merge_group:
  workflow_dispatch:
jobs:
  build-drv:
    runs-on: ubuntu-latest
    container:
      image: quay.io/fedora/fedora-minimal:${{ matrix.version }}
    strategy:
      matrix:
        version: [40, 41]
      fail-fast: false
    steps:
      - name: Install build env
        run: |
          if command -v dnf5 &> /dev/null; then alias dnf=dnf5; fi
          dnf install tar curl gzip git -y
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run build script
        run: |
          echo ${{ matrix.version }}
          rpm -E '%fedora.%_arch'
          # IS_LOCAL_BUILD=0
          # $GITHUB_WORKSPACE/scripts/build-nvidia-drv.sh
