name: Build Nvidia drivers
on:
  pull_request:
  merge_group:
  workflow_dispatch:
    
jobs:
  container-job:
    runs-on: ubuntu-latest
    container:
      image: quay.io/fedora/fedora-minimal:40
      volumes:
        - ./:/depot
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run build script
        run: cd /depot && ls && /tmp/scripts/build-nvidia-drv.sh
